name       : perl-ipc-run3
version    : 0.048
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/IPC-Run3-0.048.tar.gz : 3d81c3cc1b5cff69cca9361e2c6e38df0352251ae7b41e2ff3febc850e463565
license    : GPL-2.0
component  : programming.perl
summary    : IPC::Run3 - run a subprocess in batch mode (a la system) on Unix
description: |
    IPC::Run3 - run a subprocess in batch mode (a la system) on Unix
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
