name       : perl-ipc-run3
version    : 0.048
release    : 9
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/IPC-Run3-0.048.tar.gz : 3d81c3cc1b5cff69cca9361e2c6e38df0352251ae7b41e2ff3febc850e463565
license    : Artistic-2.0
component  : programming.perl
summary    : IPC::Run3 - run a subprocess in batch mode (a la system) on Unix
description: |
    This module allows you to run a subprocess and redirect stdin, stdout, and/or stderr to files and perl data structures.  It aims to satisfy 99% of the need for using system, qx, and open3 with a simple, extremely Perlish API and none of the bloat and rarely used features of IPC::Run.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
